"""add snmp fields to credential_profile

Revision ID: 184fc651b7fc
Revises: 93239452ccc8
Create Date: 2026-04-08 22:37:08.110106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184fc651b7fc'
down_revision = '93239452ccc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snmp_version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('snmp_community', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snmp_auth_proto', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('snmp_auth_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snmp_priv_proto', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('snmp_priv_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_profile', schema=None) as batch_op:
        batch_op.drop_column('snmp_priv_key')
        batch_op.drop_column('snmp_priv_proto')
        batch_op.drop_column('snmp_auth_key')
        batch_op.drop_column('snmp_auth_proto')
        batch_op.drop_column('snmp_community')
        batch_op.drop_column('snmp_version')

    # ### end Alembic commands ###
