"""add smb_transfers table

Revision ID: 3fb65620c35f
Revises: 184fc651b7fc
Create Date: 2026-05-16 07:19:50.051146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb65620c35f'
down_revision = '184fc651b7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smb_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.String(length=64), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('smb_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smb_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smb_transfers_backup_id'), ['backup_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smb_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smb_transfers_backup_id'))

    op.drop_table('smb_transfers')
    # ### end Alembic commands ###
